### ISSUE TITLE
jekyll-pwa-plugin.rb:161:in `block in <module:Jekyll>': undefined local 

### ISSUE THREAD

**Issue by mswbull** [lavas-project/jekyll-pwa#39]
Since upgrading, I receive the following build error. Any guidance would be greatly appreciated?

**/usr/gem/gems/jekyll-pwa-plugin-5.1.5/lib/jekyll-pwa-plugin.rb:161:in `block in <module:Jekyll>': undefined local variable or method `page' for Jekyll:Module (NameError)**

from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/hooks.rb:103:in `block in trigger'
from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/hooks.rb:102:in `each'
from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/hooks.rb:102:in `trigger'
from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/document.rb:392:in `trigger_hooks'
from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/site.rb:548:in `render_regenerated'
from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/site.rb:532:in `block (2 levels) in render_docs'
from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/site.rb:531:in `each'
from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/site.rb:531:in `block in render_docs'
from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/site.rb:530:in `each_value'
from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/site.rb:530:in `render_docs'
from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/site.rb:210:in `render'
from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/site.rb:80:in `process'
from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/command.rb:28:in `process_site'
from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:65:in `build'
from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:36:in `process'
from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `each'
from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
from /usr/gem/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
from /usr/gem/gems/jekyll-4.2.0/exe/jekyll:15:in `<top (required)>'
from /usr/local/bundle/bin/jekyll:29:in `load'
from /usr/local/bundle/bin/jekyll:29:in `<main>'

**Comment by bm1549** [comment]
I'm having the same issue

**Comment by mswbull** [comment]
Any update here? Thoughts on a fix?

**Comment by kalwalt** [comment]
i have the same issue, it could be some incompatibility between jekyll version and the plugin?

**Comment by yshmarov** [comment]
having the same when bundle updating to 5.1.5

```
/home/ubuntu/.rvm/gems/ruby-2.6.3/gems/jekyll-pwa-plugin-5.1.5/lib/jekyll-pwa-plugin.rb:161:in `block in <module:Jekyll>': undefined local variable or method `page' for Jekyll:Module (NameError)
```

source of the problem: https://github.com/lavas-project/jekyll-pwa/blob/master/lib/jekyll-pwa-plugin.rb#L161


and the commit that likely introduced the problem: https://github.com/lavas-project/jekyll-pwa/commit/a3af93c64775a96e926d2d7a2b2f65b7f6f46978#diff-4e52afc06c7bc2b8f0a305bcb7eab8cf0ddcf58f44c26dbc2bc52f0eec14e58cR161

**Comment by yshmarov** [comment]
until fixed, I'm freezing my gem version `gem 'jekyll-pwa-plugin', "= 2.2.3"`

**Comment by vidhyav656** [comment]
> gem 'jekyll-pwa-plugin', "= 2.2.3"

Thanks!! works well.
